server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: client-consumer

management:
  endpoints:
    web:
      exposure:
        include: "*"

custom:
  rest:
    connection:
      connection-request-timeout: 3000
      connect-timeout: 3000
      read-timeout: 3000