server:
  port: 1112

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  name: user provider

spring:
  application:
    name: user-provider
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8761/admin
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#spring.boot.admin.client.enabled = true
#spring.boot.admin.url=http://192.168.3.126:8888/
#management.security.enabled= false