server:
  port: 1112

management:
  security:
    enabled: false

info:
  name: user provider

spring:
  application:
    name: user-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/