server:
  port: 1112

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  name: user provider

spring:
  application:
    name: user-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
