server:
  port: 2221

#eureka:
#  client:
#    service-url: http://localhost:8761/eureka/
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    server:
#      enableSelfPreservation: false

#  instance:
#    statusPageUrlPath: http://localhost:8761/info
#    healthCheckUrlPath: ${management.context-path}/health
#    status-page-url-path: ${management.context-path}/info
#    health-check-url-path: ${management.context-path}/health

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.exampledriven.eureka: DEBUG

spring:
  application:
    name: service-cloud