server:
  port: 2000


management:
  security:
    enabled: false

spring:
  application:
    name: movie-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



